### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by ZarelaZanabria** [marimeli/lim20181-Track-FE-markdown-list#10]
Hola Melisa , quiero darte una recomendación.

- Primero trata de ordenar bien tus carpetas. Lo recomendable es que separes tu código para realizar los comandos y lo que va realizar tu librería. 

[![1](https://user-images.githubusercontent.com/38471200/45061720-5773db80-b06b-11e8-87f3-55c21e0c9f55.JPG)
](url) 
 
Aquí te muestra un organización mejor de tu archivos. 

![2](https://user-images.githubusercontent.com/38471200/45061911-16c89200-b06c-11e8-8fe3-ab7b4d5ca2f1.JPG).

- Bueno en el archivo cli.js tienes que incluir el siguiente código, esto permite realizar los comandos de lineas que tienes que mandar a la terminal.

![3](https://user-images.githubusercontent.com/38471200/45061993-8c346280-b06c-11e8-868d-c35d70a4a5ba.JPG)

- Bueno ahora en el archivo INDEX.JS solo tiene que ir las funciones que deseas realzar.  Te recomiendo utilizar las siguientes dependencias. Ya que vas a trabajar con promesas para poder validar el link. Tal vez por eso no te corre el código.
![4](https://user-images.githubusercontent.com/38471200/45062184-6eb3c880-b06d-11e8-8451-166b5c1b44f8.JPG)

https://github.com/bitinn/node-fetch
![5](https://user-images.githubusercontent.com/38471200/45062343-1af5af00-b06e-11e8-813b-042aca949345.JPG)

- Para poder Leer los archivos de un link de Markdown  puedes utilizar la librería Marked.

- Veo también que estas realizando testing me parece muy bien. Te doy unos tips. Tienes que  requerir el archivo index.js ya que ahi se encuentra la función de mdLinks.
![7](https://user-images.githubusercontent.com/38471200/45062502-d28ac100-b06e-11e8-88dc-60a0dcc497f8.JPG)

Te dejo un ejemplo para que puedas realzar tus test.
![8](https://user-images.githubusercontent.com/38471200/45062538-f948f780-b06e-11e8-87d4-fed1ad66cb84.JPG)

https://jestjs.io/

**Comment by lissavcasas** [comment]
¡Muchísimas gracias por el feedback, Zarela! Ya estoy trabajando en ello.
